version: "3.8"

services:

  flaskapp:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: